CREATE TABLE IF NOT EXISTS syslog.rh_plaza (
    id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    clave VARCHAR(30) NOT NULL,
    descr VARCHAR(55),
    tipo ENUM('DEFINITIVA', 'TEMPORAL') NOT NULL DEFAULT 'TEMPORAL',
    clave_puesto INTEGER UNSIGNED NOT NULL,
    activa TINYINT NOT NULL DEFAULT 1,
    visible TINYINT NOT NULL DEFAULT 1,
    depto INTEGER UNSIGNED,
    clave_descanso CHAR(2) NOT NULL,
    clave_jornada INTEGER UNSIGNED NOT NULL,
    fec_creacion DATE DEFAULT NULL,
    residencia VARCHAR(60) DEFAULT NULL,
    localidad VARCHAR(60) DEFAULT NULL,
    taller VARCHAR(60) DEFAULT NULL,
    instalacion VARCHAR(60) DEFAULT NULL,
    funcion VARCHAR(60) DEFAULT NULL,
    actividad VARCHAR(60) DEFAULT NULL,
    grupo VARCHAR(40) DEFAULT NULL,
    sirhn INTEGER UNSIGNED,
    posfin INTEGER UNSIGNED,
    PRIMARY KEY(id),
    INDEX IDX_clave_plaza(clave ASC),

    INDEX IDX_clave_descanso(clave_descanso ASC),
    CONSTRAINT FK_clave_descanso FOREIGN KEY(clave_descanso) REFERENCES syslog.rh_descanso(clave)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,

    INDEX IDX_clave_jornada(clave_jornada ASC),
    CONSTRAINT FK_clave_jornada FOREIGN KEY(clave_jornada) REFERENCES syslog.rh_jornada(clave) 
        ON DELETE CASCADE 
        ON UPDATE NO ACTION,

    INDEX IDX_clave_puesto(clave_puesto ASC),
    CONSTRAINT FK_clave_puesto FOREIGN KEY(clave_puesto) REFERENCES syslog.rh_puesto(clave)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8 COLLATE=utf8_spanish_ci;


INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028400   00001', 'Auxiliar Administrativo "F" ', 'DEFINITIVA', 221804, 1, 1, NULL, 'SD', 0, 'ALTAMIRA', NULL, NULL, 'ADMINISTRATIVO', 'TRANSP. PERSONAL', 'CHOFERES', 41610, 41610);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00031', 'Oficinista de Cuarta ', 'DEFINITIVA', 164406, 1, 1, NULL, 'SD', 0, 'ALTAMIRA', NULL, NULL, 'ADMINISTRATIVO', 'TRANSP. PERSONAL', 'CHOFERES', 36578, 36578);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00090', 'Oficinista de Cuarta ', 'DEFINITIVA', 164406, 1, 1, NULL, 'SD', 0, 'ALTAMIRA', NULL, NULL, 'ADMINISTRATIVO', 'TRANSP. PERSONAL', 'CHOFERES', 36574, 36574);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00027', 'Operario de Primera (Electricista) ', 'DEFINITIVA', 216309, 1, 1, NULL, 'SD', 0, 'EBANO', NULL, NULL, NULL, 'TRANSP. MATERIALES', 'TALLERES', 36768, 36768);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00024', 'Operario Especialista (Electricista) ', 'DEFINITIVA', 236309, 1, 1, NULL, 'SD', 0, 'EBANO', NULL, NULL, NULL, 'TRANSP. MATERIALES', 'TALLERES', 36999, 36999);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00102', 'Obrero General ', 'DEFINITIVA', 86107, 1, 1, NULL, 'D', 7, 'EBANO', NULL, NULL, NULL, 'TRANSP. MATERIALES', 'PESADO', 37164, 37164);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00106', 'Obrero General ', 'DEFINITIVA', 86107, 1, 1, NULL, 'D', 7, 'EBANO', NULL, NULL, NULL, 'TRANSP. MATERIALES', 'PESADO', 37166, 37166);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00099', 'Obrero General ', 'DEFINITIVA', 86107, 1, 1, NULL, 'D', 7, 'EBANO', NULL, NULL, NULL, 'TRANSP. MATERIALES', 'PESADO', 37733, 37733);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00107', 'Obrero General ', 'DEFINITIVA', 86107, 1, 1, NULL, 'D', 7, 'EBANO', NULL, NULL, NULL, 'TRANSP. MATERIALES', 'PESADO', 37158, 37158);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24025500   60000', 'AUXILIAR ADMINISTRATIVO “D”', 'DEFINITIVA', 241804, 1, 1, NULL, 'SD', 0, 'ALTAMIRA', NULL, NULL, 'ADMINISTRATIVO', 'TRANSP. LIQUIDOS', 'ADMVO', 20858741, 20858741);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00008', 'AUXILIAR ADMINISTRATIVO “D”', 'DEFINITIVA', 241804, 1, 1, NULL, 'SD', 0, 'ALTAMIRA', NULL, NULL, 'ADMINISTRATIVO', NULL, 'ADMVO', 20858024, 20858024);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   00001', 'OPERADOR “A” DE CAPTURA DE DATOS', 'DEFINITIVA', 232907, 1, 1, NULL, 'SD', 0, 'ALTAMIRA', NULL, NULL, 'ADMINISTRATIVO', 'TRANSP. PERSONAL', 'ADMVO', 20858035, 20858035);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00004', 'ENCARGADO “D” (OTROS)', 'DEFINITIVA', 209601, 1, 1, NULL, 'SD', 0, 'ALTAMIRA', NULL, NULL, 'ADMINISTRATIVO', NULL, 'ADMVO', 20857955, 20857955);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00005', 'OFICINISTA DE TERCERA', 'DEFINITIVA', 184406, 1, 1, NULL, 'SD', 0, 'ALTAMIRA', NULL, NULL, 'ADMINISTRATIVO', 'TRANSP. PERSONAL', 'ADMVO', 20857935, 20857935);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('112410002AL 20903338', 'ESPECIALISTA TÉCNICO "D"', 'DEFINITIVA', 331102, 1, 1, NULL, 'SD', 0, 'ALTAMIRA', NULL, NULL, 'ADMINISTRATIVO', 'ADMINISTRACION', 'ADMVO', 20903338, 20903338);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028900   60000', NULL, 'DEFINITIVA', 291710, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'OFICINA LOGISTICA', 'ADMINISTRATIVO', 'ADMINISTRACION', 'ADMVO', 20864044, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00007', NULL, 'DEFINITIVA', 232907, 1, 1, 23816002, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'EDIFICIO ADMINISTRATIVO', 'ADMINISTRATIVO', 'ADMINISTRACION', 'ADMVO', 20858033, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   00003', NULL, 'DEFINITIVA', 184406, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'OFICINA LOGISTICA', 'ADMINISTRATIVO', 'ADMINISTRACION', 'ADMVO', 20857934, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10001', NULL, 'DEFINITIVA', 268101, 1, 1, 23816002, 'V', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'OFICINA LOGISTICA', 'MANDO MEDIO', 'TRANSP. MATERIALES', 'MANDO', 20858038, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10002', NULL, 'DEFINITIVA', 255211, 1, 1, 23816002, 'S', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'MANDO MEDIO', 'TRANSP. MATERIALES', 'MANDO', 20858094, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402890030 04025', NULL, 'TEMPORAL', 235209, 1, 1, 23816100, 'S', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', NULL, 'PESADO', 20869174, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10003', 'EQUIPO PESADO', 'DEFINITIVA', 235209, 1, 1, 23816100, 'V', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857967, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10004', 'EQUIPO PESADO', 'DEFINITIVA', 235209, 1, 1, 23816100, 'J', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857970, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10005', 'EQUIPO PESADO', 'DEFINITIVA', 235209, 1, 1, 23816100, 'M', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857961, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10006', 'EQUIPO PESADO', 'DEFINITIVA', 235209, 1, 1, 23816100, 'V', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857968, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402860030 30303', NULL, 'TEMPORAL', 227201, 1, 1, 23816100, 'M', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20858028, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402860030 00005', 'MOVIMIENTOS', 'TEMPORAL', 216203, 0, 1, NULL, 'D', 7, 'PACAEB', 'EBANO', 'TALLER LOGISTICA', 'PESADO', NULL, 'PESADO', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402860030 93001', NULL, 'TEMPORAL', 216203, 1, 1, 23816100, 'X', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', NULL, 'PESADO', 20857969, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402860030 31012', NULL, 'TEMPORAL', 216202, 1, 1, 23816100, 'SD', 0, 'PACAEB', 'CACALILAO', 'PLANTA CENTRAL', 'PESADO', NULL, 'PESADO', 20857958, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402860030 94100', NULL, 'TEMPORAL', 216202, 1, 1, 23816100, 'D', 7, 'PACAEB', 'EBANO', 'PLANTA CENTRAL', 'PESADO', NULL, 'PESADO', 20857971, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10007', 'INSTL. DE PRODUCCIÓN', 'DEFINITIVA', 178502, 1, 1, 23816100, 'D', 7, 'PACAEB', 'EBANO', 'TALLER PRODUCCIÓN', 'SEMI-PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857926, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10008', NULL, 'DEFINITIVA', 178502, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'SEMI-PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857928, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10009', NULL, 'DEFINITIVA', 178502, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'SEMI-PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857931, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10010', 'BATS. Y CARGADEROS PANUCO', 'DEFINITIVA', 178502, 1, 1, 23816100, 'SD', 0, 'PACAEB', 'PANUCO', 'EST. SAN MANUEL', 'SEMI-PESADO', 'TRANSP. LIQUIDOS', 'PESADO', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10011', NULL, 'DEFINITIVA', 178502, 1, 1, 23816100, 'SD', 0, 'PACAEB', 'EBANO', 'TALLER PRODUCCION', 'SEMI-PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857927, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10012', NULL, 'DEFINITIVA', 178502, 1, 1, 23816002, 'S', 7, 'CPO. TAMPS.', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'SEMI-PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857925, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10013', NULL, 'DEFINITIVA', 178502, 1, 1, 23816100, 'SD', 0, 'PACAEB', 'EBANO', 'TALLER PRODUCCIÓN', 'SEMI-PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857906, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10014', NULL, 'DEFINITIVA', 176202, 1, 1, 23816002, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER ELECTRICO', 'SEMI-PESADO', 'TRANSP. MATERIALES', 'PESADO', 20857903, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402890030 04026', NULL, 'TEMPORAL', 116209, 1, 1, 23816100, 'D', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', NULL, 'PESADO', 20869175, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402890030 04027', NULL, 'TEMPORAL', 116209, 1, 1, 23816100, 'D', 7, 'PACAEB', 'CACALILAO', 'PLANTA CENTRAL', 'PESADO', NULL, 'PESADO', 20869183, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402860030 00007', NULL, 'TEMPORAL', 86107, 0, 1, NULL, 'SD', 0, 'PACAEB', 'CACALILAO', 'TALLERES PRODUCCION', 'GENERAL', NULL, 'PESADO', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402860030 00604', NULL, 'TEMPORAL', 86107, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', NULL, 'PESADO', 20858125, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10037', NULL, 'DEFINITIVA', 86107, 1, 1, 23816100, 'V', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20858150, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10038', NULL, 'DEFINITIVA', 86107, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20858149, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10039', NULL, 'DEFINITIVA', 86107, 1, 1, 23816100, 'M', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20858148, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10040', NULL, 'DEFINITIVA', 86107, 1, 1, 23816100, 'V', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20858146, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10041', NULL, 'DEFINITIVA', 86107, 0, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', NULL, 'PESADO', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10042', NULL, 'DEFINITIVA', 86107, 1, 1, 23816100, 'X', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20858143, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10043', NULL, 'DEFINITIVA', 86107, 1, 1, 23816100, 'M', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', 'TRANSP. MATERIALES', 'PESADO', 20858142, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402860030 30301', NULL, 'TEMPORAL', 86107, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', NULL, 'PESADO', 20858174, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402860030 31129', NULL, 'TEMPORAL', 86107, 1, 1, 23816100, 'J', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'PESADO', NULL, 'PESADO', 20858173, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10040797', NULL, 'TEMPORAL', 228101, 0, 1, 23816100, 'D', 4, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10040798', NULL, 'TEMPORAL', 228101, 0, 1, 23816100, 'D', 4, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10016', 'RUTA FIJA BOMB. TAMPS.', 'DEFINITIVA', 158502, 1, 1, 23816100, 'J', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857870, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10017', 'RUTA FIJA BOMB. CONST.', 'DEFINITIVA', 158502, 1, 1, 23816100, 'X', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857871, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10023', 'RUTA FIJA PLANTA DE INYECCION', 'DEFINITIVA', 158502, 1, 1, 23816100, 'J', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857895, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10024', 'RUTA FIJA PLANTA DE INYECCION', 'DEFINITIVA', 158502, 1, 1, 23816100, 'M', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857890, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10025', 'RUTA FIJA BOMB. CONST.', 'DEFINITIVA', 158502, 1, 1, 23816100, 'L', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857876, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10026', 'RUTA FIJA BOMB. CONST.', 'DEFINITIVA', 158502, 1, 1, 23816100, 'V', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857868, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10027', 'RUTA FIJA BOMB. TAMPS.', 'DEFINITIVA', 158502, 1, 1, 23816100, 'S', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857889, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10028', 'RUTA PLANTA DE INYECCION', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'CHOFER', NULL, 'GUARDIAS', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10030', 'RUTA PM-5603', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'CHOFER', NULL, 'GUARDIAS', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10031', 'RUTA PM-5603', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'CHOFER', NULL, 'GUARDIAS', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10032', 'RUTA FIJA RELEVO BOMB. TAMPS/BOMB. CONST.', 'DEFINITIVA', 158502, 1, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857892, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10033', 'RUTA BOMB. CONST.', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'CHOFER', NULL, 'GUARDIAS', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10035', 'RUTA FIJA RELEVO PLANTA INYECC/COMPRESORAS III', 'DEFINITIVA', 158502, 1, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857894, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10036', 'RUTA VIJA BOMB. TAMPS', 'DEFINITIVA', 158502, 1, 1, 23816100, 'M', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', 'TRANSP. PERSONAL', 'GUARDIAS', 20857888, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 00030503', 'RUTA VARIABLE CR', 'TEMPORAL', 158502, 1, 1, 23816100, 'S', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', 20859468, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 00050901', 'RUTA COMPRESORAS III', 'TEMPORAL', 158502, 1, 1, 23816100, 'L', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', 20861497, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 00050904', NULL, 'TEMPORAL', 158502, 0, 0, 23816100, 'D', 5, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'GUARDIAS', NULL, 'GUARDIAS', 20861600, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10025020', 'RUTA VARIABLE PM-5521', 'TEMPORAL', 158502, 1, 1, 23816100, 'L', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', 20873539, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10025021', 'RUTA COMPRESORAS III', 'TEMPORAL', 158502, 1, 1, 23816100, 'X', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', 20873540, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10025023', 'RUTA COMPRESORAS III', 'TEMPORAL', 158502, 1, 1, 23816100, 'S', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', 20873541, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10025024', 'RUTA VARIABLE CR', 'TEMPORAL', 158502, 1, 1, 23816100, 'M', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', 20873542, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10025025', 'RUTA VARIABLE PM-1312', 'TEMPORAL', 158502, 1, 1, 23816100, 'J', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', 20873543, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10040793', 'RUTA PLANTA DE INYECCION', 'TEMPORAL', 158502, 1, 1, 23816100, 'S', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', 20877252, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10040796', 'RUTA VARIABLE RELEVO 5521/CR', 'TEMPORAL', 158502, 1, 1, 23816100, 'D', 2, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DESPACHO DE GUARDIAS', 'GUARDIAS', NULL, 'GUARDIAS', 20877253, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10015', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'SD', 0, 'PACAEB', 'EBANO', 'OFICINAS DE OPN. DE POZOS', 'CHOFER', 'TRANSP. PERSONAL', 'CHOFERES', 20857869, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10018', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'CHOFER', 'TRANSP. PERSONAL', 'CHOFERES', 20857872, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10019', 'PLANTA CENTRAL', 'DEFINITIVA', 158502, 1, 1, 23816100, 'SD', 0, 'PACAEB', 'CACALILAO', 'PLANTA CENTRAL', 'CHOFER', 'TRANSP. PERSONAL', 'CHOFERES', 20857873, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10020', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'CHOFER', 'TRANSP. PERSONAL', 'CHOFERES', 20857874, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10021', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'CHOFER', 'TRANSP. PERSONAL', 'CHOFERES', 20857875, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10022', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'CHOFER', 'TRANSP. PERSONAL', 'CHOFERES', 20857896, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10029', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'CHOFER', 'TRANSP. PERSONAL', 'CHOFERES', 20857891, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   10034', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'TALLER LOGISTICA', 'CHOFER', 'TRANSP. PERSONAL', 'CHOFERES', 20857893, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00047', 'CORROSIÓN', 'DEFINITIVA', 178502, 1, 1, 23816002, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DUCTOS Y VIAS DE ACCESO', 'SEMI-PESADO', 'ASSIGN', 'ASIGN', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24027200   00007', NULL, 'DEFINITIVA', 158502, 1, 1, 23872000, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'SERVICIOS GENERALES', 'CHOFER', 'ASSIGN', 'ASIGN', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24027200   00029', NULL, 'DEFINITIVA', 158502, 1, 1, 23872000, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'ALMACEN', 'CHOFER', 'ASSIGN', 'ASIGN', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2402890030 04050', NULL, 'TEMPORAL', 158502, 1, 1, NULL, 'D', 7, 'CD. MADERO', 'SECTOR ARENQUE', 'BAT. ARENQUE', 'CHOFER', NULL, 'CHOFERES', 20855184, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00064', 'TANQUES Y TUBERIAS', 'DEFINITIVA', 156207, 1, 1, 23816002, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'DUCTOS Y VIAS DE ACCESO', 'CHOFER', 'ASSIGN', 'ASIGN', NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00081', NULL, 'DEFINITIVA', 216203, 0, 1, 23816100, 'D', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'OFICINA LOGISTICA', 'PESADO', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24027200   00030', NULL, 'TEMPORAL', 158502, 0, 1, 23872000, 'V', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'CHOFER', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 00030501', 'RUTA PM-5521', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 00030502', 'RUTA PM-5521', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 00050902', 'RUTA DCM-722', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 00050903', 'RUTA DCM-722', 'TEMPORAL', 158502, 0, 1, 23816100, 'S', 7, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'ECOLOGIA', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10025022', 'RUTA DS-663', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10025076', 'RUTA DS-664', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10040790', 'RUTA DS-665', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10040791', 'RUTA DS-665', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10040792', 'RUTA DS-665', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10040794', 'RUTA DS-667', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('2381610030 10040795', 'RUTA DS-667', 'TEMPORAL', 158502, 0, 1, 23816100, 'D', 1, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'GUARDIAS', 'GUARDIAS', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00065', NULL, 'TEMPORAL', 156207, 0, 1, 23816002, 'SD', 0, NULL, NULL, NULL, 'CHOFER', NULL, NULL, NULL, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028600   00002', NULL, 'DEFINITIVA', 221804, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'EDIFICIO ADMINISTRATIVO', 'ADMINISTRATIVO', 'ADMINISTRACION', NULL, 20858009, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('24028500   00009', NULL, 'DEFINITIVA', 243513, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'EDIFICIO ADMINISTRATIVO', 'ADMINISTRATIVO', 'TRANSP. LIQUIDOS', NULL, 20858022, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('82024910   00001', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'TAMPICO', 'EDIFICIO AGUILA', 'CHOFER', NULL, NULL, 20858746, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('82024961   00011', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'D', 7, 'ALTAMIRA', 'TAMPICO', NULL, 'CHOFER', NULL, NULL, 20858751, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('82024981   00003', NULL, 'DEFINITIVA', 158502, 1, 1, 23816100, 'D', 7, 'ALTAMIRA', 'TAMPICO', NULL, 'CHOFER', NULL, NULL, 20858756, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('82024901   00003', NULL, 'DEFINITIVA', 234406, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'TAMPICO', NULL, 'ADMINISTRATIVO', NULL, NULL, 20858765, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('112410002AL 20903229', NULL, 'DEFINITIVA', 371102, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'EDIFICIO ADMINISTRATIVO', 'ADMINISTRATIVO', 'TRANSP. LIQUIDOS', NULL, 20903229, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('112410002AL 20903304', NULL, 'DEFINITIVA', 351102, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'EDIFICIO ADMINISTRATIVO', 'ADMINISTRATIVO', 'TRANSP. MATERIALES', NULL, 20903304, NULL);
INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('20926100PR 10073243', NULL, 'DEFINITIVA', 331102, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'EDIFICIO ADMINISTRATIVO', 'ADMINISTRATIVO', 'TRANSP. PERSONAL', NULL, 20903338, NULL);


INSERT INTO syslog.rh_plaza (clave, descr, tipo, clave_puesto, activa, visible, depto, clave_descanso, clave_jornada, residencia, localidad, taller, funcion, actividad, grupo, sirhn, posfin) VALUES ('23816002AL 00190731', NULL, 'DEFINITIVA', 331102, 1, 1, 23816100, 'SD', 0, 'ALTAMIRA', 'CAMPO TAMAULIPAS', 'EDIFICIO ADMINISTRATIVO', 'ADMINISTRATIVO', 'TRANSP. LIQUIDOS', NULL, 20903229, NULL);




UPDATE syslog.rh_plaza SET visible=0 WHERE activa=0;
UPDATE syslog.rh_plaza SET visible=0 WHERE clave='238161003000050904';

ALTER TABLE syslog.rh_plaza ADD escalafon TINYINT;




UPDATE syslog.rh_plaza SET escalafon=10 WHERE TIPO='DEFINITIVA' AND ACTIVA=1 AND (CLAVE LIKE '24028600%' OR CLAVE LIKE '24028900%' OR CLAVE LIKE '24027200%');

